export const TEMPLATE_CONFIG = {
    TEMPLATE_DIR: "./templates/",
    INTERVALO_FRAMES: 1000,
    DURACION_FADE: 600,
    INTERVALO_PRODUCTOS: 1000,
    DURACION_FADE_PRODUCTO: 400,
    PRODUCTOS_POR_PAGINA: 6,
};
